// src/components/TradingViewWidget.tsx
import { memo } from "react";
import useTradingViewWidget from "@/hooks/useTradingViewWidget";
import { cn } from "@/lib/utils";

interface TradingViewWidgetProps {
  title?: string;
  scriptUrl: string;
  config: Record<string, unknown>;
  height?: number;
  className?: string;
}

const TradingViewWidget = ({
  title,
  scriptUrl,
  config,
  height = 600,
  className,
}: TradingViewWidgetProps) => {
  const containerRef = useTradingViewWidget(scriptUrl, config, height);

  return (
    <div className="w-full">
      {title && (
        <h3 className="mb-5 text-2xl font-semibold text-gray-100">{title}</h3>
      )}
      <div
        className={cn("tradingview-widget-container", className)}
        ref={containerRef}
      >
        <div
          className="tradingview-widget-container__widget"
          style={{ height, width: "100%" }}
        />
      </div>
    </div>
  );
};

export default memo(TradingViewWidget);

// app/components/TradingViewWidget.vue
<script setup lang="ts">
import { computed } from "vue";
import { useTradingViewWidget } from "@/composables/useTradingViewWidget";

interface TradingViewWidgetProps {
  title?: string;
  scriptUrl: string;
  config: Record<string, unknown>;
  height?: number;
  className?: string;
}

const props = withDefaults(defineProps<TradingViewWidgetProps>(), {
  height: 600,
  className: "",
});

const containerRef = useTradingViewWidget(
  props.scriptUrl,
  props.config,
  props.height,
);
</script>

<template>
  <div class="w-full">
    <h3 v-if="title" class="mb-5 text-2xl font-semibold text-gray-100">
      {{ title }}
    </h3>
    <div
      class="tradingview-widget-container"
      :class="props.className"
      ref="containerRef"
    >
      <div
        class="tradingview-widget-container__widget"
        :style="{ height: `${height}px`, width: '100%' }"
      />
    </div>
  </div>
</template>
