// app/components/Header.vue
<template>
  <header class="header sticky top-0">
    <div class="header-wrapper container">
      <NuxtLink to="/">
        <img
          src="/icons/logo.svg"
          alt="logo"
          width="140"
          height="32"
          class="h-8 w-auto cursor-pointer"
        />
      </NuxtLink>
      <nav class="hidden sm:block">
        <NavItems />
      </nav>
      <UserDropdown />
    </div>
  </header>
</template>

<script setup lang="ts">
import NavItems from "./NavItems.vue";
import UserDropdown from "./UserDropdown.vue";
</script>

<style scoped></style>

// src/components/Header.tsx
import NavItems from "@/components/NavItems";

const Header = () => {
  return (
    <header className="header sticky top-0">
      <div className="header-wrapper container">
        <a href="/">
          <img
            src="/assets/icons/logo.svg"
            alt="Signalist logo"
            width={140}
            height={32}
            className="h-8 w-auto cursor-pointer"
          />
        </a>
        <nav className="hidden sm:block">
          <NavItems />
        </nav>
      </div>
    </header>
  );
};
export default Header;
